//Source code generated by AppGPT (www.appgpt.tech)

//Class to create tables and seed new database
import { DataSource } from 'typeorm';
import { DBConfiguration } from './Configuration';
import { SettingsEntity } from './db/Settings.entity';
//autogenerate imports based on resources
import { SparePartsEntity } from './db/SpareParts.entity';
import { EngineOilEntity } from './db/EngineOil.entity';
import { CategoriesEntity } from './db/Categories.entity';

export class Database {
  static dbConfiguration: DBConfiguration;
  public static ds: DataSource;

  static async Initialize(dbConfiguration: DBConfiguration) {
    Database.dbConfiguration = dbConfiguration;
    let dbConfig: any = dbConfiguration as any;
    //Autogenerate entities array from resource names

    dbConfig.entities = [
      SettingsEntity,
      SparePartsEntity,
      EngineOilEntity,
      CategoriesEntity,
    ];
    Database.ds = new DataSource(dbConfig);
    await Database.ds.initialize();

    //TODO: Drop all tables

    await Database.Seed();
  }
  static async Seed() {
    let data: any = {
      SpareParts: [
        {
          name: 'name 1',
          price: 0.18,
          compatibility: 'compatibility 1',
          stockQuantity: 1,
          id: 7,
        },
        {
          name: 'name 2',
          price: 0.53,
          compatibility: 'compatibility 2',
          stockQuantity: 2,
          id: 8,
        },
        {
          name: 'name 3',
          price: 0.64,
          compatibility: 'compatibility 3',
          stockQuantity: 3,
          id: 80,
        },
        {
          name: 'name 4',
          price: 0.7,
          compatibility: 'compatibility 4',
          stockQuantity: 4,
          id: 87,
        },
        {
          name: 'name 5',
          price: 0.1,
          compatibility: 'compatibility 5',
          stockQuantity: 5,
          id: 72,
        },
      ],
      EngineOil: [
        {
          name: 'name 1',
          price: 0.89,
          compatibility: 'compatibility 1',
          stockQuantity: 1,
          id: 89,
        },
        {
          name: 'name 2',
          price: 0.06,
          compatibility: 'compatibility 2',
          stockQuantity: 2,
          id: 44,
        },
        {
          name: 'name 3',
          price: 0.18,
          compatibility: 'compatibility 3',
          stockQuantity: 3,
          id: 46,
        },
        {
          name: 'name 4',
          price: 0.69,
          compatibility: 'compatibility 4',
          stockQuantity: 4,
          id: 79,
        },
        {
          name: 'name 5',
          price: 0.11,
          compatibility: 'compatibility 5',
          stockQuantity: 5,
          id: 59,
        },
      ],
      Categories: [
        {
          categoryName: 'categoryName 1',
          description: 'description 1',
          stockQuantity: 1,
          id: 98,
        },
        {
          categoryName: 'categoryName 2',
          description: 'description 2',
          stockQuantity: 2,
          id: 9,
        },
        {
          categoryName: 'categoryName 3',
          description: 'description 3',
          stockQuantity: 3,
          id: 86,
        },
        {
          categoryName: 'categoryName 4',
          description: 'description 4',
          stockQuantity: 4,
          id: 3,
        },
        {
          categoryName: 'categoryName 5',
          description: 'description 5',
          stockQuantity: 5,
          id: 59,
        },
      ],
    };
    //Autogenerate multiple such calls ie for each resource and its data object
    let isSeeded = await this.IsSeeded();
    //if (!isSeeded) {
    //forcing app recreation
    if (true) {
      console.log('   Seeding database...');
      await this.SeedResource('SparePartsEntity', data.SpareParts);
      await this.SeedResource('EngineOilEntity', data.EngineOil);
      await this.SeedResource('CategoriesEntity', data.Categories);
      await this.SeedResource('SettingsEntity', {
        settingname: 'isSeeded',
        settingvalue: 'true',
      });
    } else {
      console.log('   Database seeded already!');
    }
  }
  static async IsSeeded() {
    const repo = Database.ds.getRepository('SettingsEntity');
    let rec: any = await repo.findOne({
      select: {
        settingname: true,
        settingvalue: true,
      },
      where: {
        settingname: 'isSeeded',
      },
    });
    if (rec && rec.settingvalue) return true;
    return false;
  }
  static async SeedResource(resourceName: any, resourceData: any) {
    const repo = Database.ds.getRepository(resourceName);
    //await repo.clear();
    console.log('   Seeding table ' + resourceName);
    await repo.upsert(resourceData, ['id']);
  }
}
