//Source code generated by AppGPT (www.appgpt.tech)
let data: any = {
  defaultData: {
    SpareParts: [
      {
        name: 'name 1',
        price: 0.18,
        compatibility: 'compatibility 1',
        stockQuantity: 1,
        id: 7,
      },
      {
        name: 'name 2',
        price: 0.53,
        compatibility: 'compatibility 2',
        stockQuantity: 2,
        id: 8,
      },
      {
        name: 'name 3',
        price: 0.64,
        compatibility: 'compatibility 3',
        stockQuantity: 3,
        id: 80,
      },
      {
        name: 'name 4',
        price: 0.7,
        compatibility: 'compatibility 4',
        stockQuantity: 4,
        id: 87,
      },
      {
        name: 'name 5',
        price: 0.1,
        compatibility: 'compatibility 5',
        stockQuantity: 5,
        id: 72,
      },
    ],
    EngineOil: [
      {
        name: 'name 1',
        price: 0.89,
        compatibility: 'compatibility 1',
        stockQuantity: 1,
        id: 89,
      },
      {
        name: 'name 2',
        price: 0.06,
        compatibility: 'compatibility 2',
        stockQuantity: 2,
        id: 44,
      },
      {
        name: 'name 3',
        price: 0.18,
        compatibility: 'compatibility 3',
        stockQuantity: 3,
        id: 46,
      },
      {
        name: 'name 4',
        price: 0.69,
        compatibility: 'compatibility 4',
        stockQuantity: 4,
        id: 79,
      },
      {
        name: 'name 5',
        price: 0.11,
        compatibility: 'compatibility 5',
        stockQuantity: 5,
        id: 59,
      },
    ],
    Categories: [
      {
        categoryName: 'categoryName 1',
        description: 'description 1',
        stockQuantity: 1,
        id: 98,
      },
      {
        categoryName: 'categoryName 2',
        description: 'description 2',
        stockQuantity: 2,
        id: 9,
      },
      {
        categoryName: 'categoryName 3',
        description: 'description 3',
        stockQuantity: 3,
        id: 86,
      },
      {
        categoryName: 'categoryName 4',
        description: 'description 4',
        stockQuantity: 4,
        id: 3,
      },
      {
        categoryName: 'categoryName 5',
        description: 'description 5',
        stockQuantity: 5,
        id: 59,
      },
    ],
  },
};
export default data;
